name: CI

on:
  push:
@@ -21,12 +22,23 @@ jobs:

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
    - name: Run unit tests
      run: |
        source venv/bin/activate
        pytest tests/unit/
    - name: Run integration tests
      run: |
        source venv/bin/activate
        pytest tests/integration/
    - name: Run E2E tests
      run: |
        source venv/bin/activate
        pytest tests/e2e/